export const PROXY_PORT = 6251;
export const JUPYTER_PORT = 6252;

export const JUMP_POINT_OPTIONS = [
  "#",
  "#study-overview",
  "#contacts-and-locations",
  "#participation-criteria",
  "#study-plan",
  "#collaborators-and-investigators",
  "#publications",
  "#study-record-dates",
  "#more-information",
  "?tab=table",
  "?tab=table#trial-contacts",
  "?tab=table#study-record-dates",
  "?tab=table#outcome-measures",
  "?tab=table#trial-description",
  "?tab=table#recruitment-information",
  "?tab=table#administrative-information",
  "?tab=table#symbol-legend",
  "?tab=results",
  "?tab=results#results-overview",
  "?tab=results#study-record-dates",
  "?tab=results#participant-flow",
  "?tab=results#baseline-characteristics",
  "?tab=results#outcome-measures",
  "?tab=results#adverse-events",
  "?tab=results#limitations-and-caveats",
  "?tab=results#collaborators-and-investigators",
  "?tab=results#publications",
  "?tab=results#more-information",
  "?tab=history",
];
