services:
  searxng:
    ports:
      - 8080:8080
    container_name: searxng
    image: docker.io/searxng/searxng:latest
    restart: unless-stopped
    environment:
      - FORMATS=html,json
    networks:
      - web
    volumes:
      - ./searxng-data:/etc/searxng:rw
networks:
  web:
    external: true
